// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ContactApp.iOS
{
	public partial class ContactDetailVC : UIViewController
	{
		public ContactDetailVC (IntPtr handle) : base (handle)
		{
		}
	}
}
