// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;
using ContactApp.Core.Entities;
using ContactApp.iOS.DataSources;

namespace ContactApp.iOS
{
	public partial class ContactsIndexController : UITableViewController
	{
		public ContactsIndexController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var contactList = new List<Contact>();

            /*for( var i = 0; i < 100; i++ )
            {
                contactList.Add(new Contact
                {
                    FullName    = $"Contact Factory {i}",
                    Phone       = $"Phone factory {i}"
                });
            }*/

            dgvContacts.Source = new ContactDS( contactList,this );

        }
    }
}
