// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;
using ContactApp.Core.Entities;
using ContactApp.Core.Repository.SQLite;
using ContactApp.iOS.DataSources;

namespace ContactApp.iOS
{
	public partial class ContactsIndexController : UITableViewController
	{
        private List<Contact> contactList;

		public ContactsIndexController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            //var contactList = new List<Contact>();

            try
            {
                contactList         = Connection.Instance.Table<Contact>().ToList();
                dgvContacts.Source  = new ContactDS(contactList, this);
            }
            catch (Exception Ex)
            {
                
            }

            bbiAddContact.Clicked += RenderContactDetailVC;

        }

        private void RenderContactDetailVC(object sender, EventArgs e)
        {

            var contactDetailVC = (ContactDetailVC) Storyboard.InstantiateViewController("ContactDetailVC");
            contactDetailVC.Contact = new Contact {
                /*FullName    = null,
                Phone       = null  */
            };
            
            this.NavigationController.PushViewController( contactDetailVC, true );
        }

        private void ReloadContactsTable()
        {
            try
            {
                contactList = Connection.Instance.Table<Contact>().ToList();
                dgvContacts.Source = new ContactDS(contactList, this);
                dgvContacts.ReloadData();
            }
            catch (Exception Ex)
            {

            }
          
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            ReloadContactsTable();
        }
    }
}
