// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ContactApp.iOS
{
	public partial class ContactShowVC : UIViewController
	{
		public ContactShowVC (IntPtr handle) : base (handle)
		{
		}
	}
}
